# toolchain32.cmake
set(CMAKE_C_FLAGS "-m32")
set(CMAKE_CXX_FLAGS "-m32")
set(CMAKE_EXE_LINKER_FLAGS "-m32")
set(CMAKE_SHARED_LINKER_FLAGS "-m32")
set(CMAKE_ASM_FLAGS "-m32")
set(BOOST_CONTEXT_ARCHITECTURE "i386" CACHE STRING "" FORCE)