X_WRAPPER(double atof, const_char_ptr s)
X_WRAPPER(int atoi, const_char_ptr s)
X_WRAPPER(long atol, const_char_ptr s)
X_WRAPPER(void_ptr calloc, size_t num, size_t size)
X_WRAPPER(int close, int fd)
X_WRAPPER(int connect, int sockfd, const_sockaddr_ptr addr, socklen_t addrlen)
X_WRAPPER(int fgetc, FILE_ptr stream)
X_WRAPPER(char_ptr fgets, char_ptr str, int n, FILE_ptr stream)
X_WRAPPER(int fclose, FILE_ptr stream)
X_WRAPPER(int fflush, FILE_ptr stream)
X_WRAPPER(size_t fread, void_ptr ptr, size_t size, size_t nmemb, FILE_ptr stream)
X_WRAPPER(void free, void_ptr ptr)
X_WRAPPER(int getc, FILE_ptr stream)
X_WRAPPER(char_ptr getenv, const_char_ptr name)
X_WRAPPER(char_ptr gets, char_ptr buffer)
X_WRAPPER(void_ptr malloc, size_t size)
X_WRAPPER(size_t malloc_usable_size, void_ptr ptr)
X_WRAPPER(int memcmp, const_void_ptr buf1, const_void_ptr buf2, size_t count)
X_WRAPPER(void_ptr memcpy, void_ptr dest, const_void_ptr src, size_t n)
X_WRAPPER(void_ptr memmove, void_ptr dest, const_void_ptr src, size_t count)
X_WRAPPER(void_ptr memset, void_ptr str, int c, size_t n)
X_WRAPPER(int open, const_char_ptr pathname, int flags)
X_WRAPPER(void perror, const_char_ptr string)
X_WRAPPER(int putc, int c, FILE_ptr stream)
X_WRAPPER(int putchar, int c)
X_WRAPPER(int puts, const_char_ptr s)
X_WRAPPER(ssize_t read, int fd, void_ptr buf, size_t count)
X_WRAPPER(void_ptr realloc, void_ptr ptr, size_t size)
X_WRAPPER(int socket, int domain, int type, int protocol)
X_WRAPPER(int strncasecmp, const_char_ptr string1, const_char_ptr string2, size_t count)
X_WRAPPER(char_ptr strcat, char_ptr dest, const_char_ptr src)
X_WRAPPER(char_ptr strchr, const_char_ptr str, int c)
X_WRAPPER(int strcmp, const_char_ptr s1, const_char_ptr s2)
X_WRAPPER(char_ptr strcpy, char_ptr dest, const_char_ptr src)
X_WRAPPER(size_t strcspn, const_char_ptr string1, const_char_ptr string2)
X_WRAPPER(size_t strlen, const_char_ptr s)
X_WRAPPER(char_ptr strncat, char_ptr string1, const_char_ptr string2, size_t count)
X_WRAPPER(int strncmp, const_char_ptr s1, const_char_ptr s2, size_t n)
X_WRAPPER(char_ptr strncpy, char_ptr string1, const_char_ptr string2, size_t count)
X_WRAPPER(char_ptr strstr, const_char_ptr string1, const_char_ptr string2)
X_WRAPPER(unsigned_long strtoul, const_char_ptr nptr, char_ptr_ptr endptr, int base)
X_WRAPPER(char_ptr strtok, char_ptr string1, const_char_ptr string2)
X_WRAPPER(long strtol, const_char_ptr nptr, char_ptr_ptr endptr, int base)
X_WRAPPER(int system, const_char_ptr command)
X_WRAPPER(int tolower, int c)
X_WRAPPER(int toupper, int c)
X_WRAPPER(ssize_t write, int fd, const_void_ptr buf, size_t count)

X_WRAPPERNOARG(int getchar)

X_DEF(void abort)
X_DEF(void assert, int x)
X_DEF(void exit, int status)
X_DEF(void_ptr mmap, void_ptr addr, size_t length, int prot, int flags, int fd, off_t offset)
X_DEF(int munmap, void_ptr addr, size_t length)
X_DEF(int vscanf, const_char_ptr format, va_list ap)
X_DEF(int vfscanf, FILE_ptr f, const_char_ptr format, va_list ap)
X_DEF(int vsscanf, const_char_ptr s, const_char_ptr format, va_list ap)
X_DEF(int vfprintf, FILE_ptr f, const_char_ptr format, va_list ap)
X_DEF(int vprintf, const_char_ptr format, va_list ap)
X_DEF(int vsprintf, char_ptr s, const_char_ptr format, va_list ap)
X_DEF(int vsnprintf, char_ptr s, size_t n, const_char_ptr format, va_list ap)

X_DEF(void __stack_chk_fail);